<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Additional Countries
            [
                'name' => 'United States',
                'currency' => 'USD',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'United Kingdom',
                'currency' => 'GBP',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Germany',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'de',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'France',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'fr',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Italy',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'it',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spain',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'es',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Canada',
                'currency' => 'CAD',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Australia',
                'currency' => 'AUD',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Japan',
                'currency' => 'JPY',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'ja',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'China',
                'currency' => 'CNY',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'zh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'India',
                'currency' => 'INR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'hi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brazil',
                'currency' => 'BRL',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'pt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mexico',
                'currency' => 'MXN',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'es',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South Korea',
                'currency' => 'KRW',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'ko',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Netherlands',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'nl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sweden',
                'currency' => 'SEK',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'sv',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Norway',
                'currency' => 'NOK',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'no',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Denmark',
                'currency' => 'DKK',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'da',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Finland',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'fi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Poland',
                'currency' => 'PLN',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'pl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Czech Republic',
                'currency' => 'CZK',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'cs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hungary',
                'currency' => 'HUF',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'hu',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Romania',
                'currency' => 'RON',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'ro',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bulgaria',
                'currency' => 'BGN',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'bg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Greece',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'el',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Portugal',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'pt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ireland',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Austria',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'de',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Switzerland',
                'currency' => 'CHF',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'de',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Belgium',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'nl',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luxembourg',
                'currency' => 'EUR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'fr',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Israel',
                'currency' => 'ILS',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'he',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Saudi Arabia',
                'currency' => 'SAR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'ar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'United Arab Emirates',
                'currency' => 'AED',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'ar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Egypt',
                'currency' => 'EGP',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'ar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South Africa',
                'currency' => 'ZAR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nigeria',
                'currency' => 'NGN',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kenya',
                'currency' => 'KES',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Argentina',
                'currency' => 'ARS',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'es',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chile',
                'currency' => 'CLP',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'es',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Colombia',
                'currency' => 'COP',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'es',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peru',
                'currency' => 'PEN',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'es',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Venezuela',
                'currency' => 'VES',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'es',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thailand',
                'currency' => 'THB',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'th',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vietnam',
                'currency' => 'VND',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'vi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indonesia',
                'currency' => 'IDR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'id',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Malaysia',
                'currency' => 'MYR',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'ms',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Singapore',
                'currency' => 'SGD',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Philippines',
                'currency' => 'PHP',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'New Zealand',
                'currency' => 'NZD',
                'garden_percent' => 0.00,
                'tariff' => 10.00,
                'price' => 10.00,
                'exchange_rate' => null,
                'dister' => null,
                'sms_gateway_id' => null,
                'payment_gateway_id' => null,
                'language' => 'en',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Use updateOrCreate to handle existing countries
        foreach ($countries as $countryData) {
            Country::updateOrCreate(
                ['name' => $countryData['name']],
                $countryData
            );
        }
    }
}
